### ISSUE TITLE
Linux/Bombs/File_Bomb/Linuxpy.txt doesn't work anymore

### ISSUE THREAD

**Issue by itJunky** [SHUR1K-N/Flipper-Zero-BadKB-Files#7]
Because downloading of https://github.com/FalsePhilosopher/BadUSB-Playground/raw/main/Ducky/USBRubberducky/library/prank/Unix-like/Linux/Bombs/File_bomb/PLTUX.py failed with 404 error.

**Comment by SHUR1K-N** [comment]
Updated path: https://raw.githubusercontent.com/FalsePhilosopher/BadUSB-Playground/main/Ducky/USBRubberducky/destructive/Unix-like/Linux/Bombs/File_bomb/PLTUX.py
